### ISSUE TITLE
concatenate_chunks.py error

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/mimtpy#12]
Hi @ranneylxr 

When I run as given by --help I get an error:
```
concatenate_chunks.py $TE/ChamanBigSenAT144.template --outdir mimtpy --datatype velocity
/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy

Traceback (most recent call last):
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 264, in <module>
    main()
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 238, in main
    if inpsdict['mimtpy.chunk'] == 'yes':
KeyError: 'mimtpy.chunk'
```
Am I doing something stupid?  When I say
```
concatenate_chunks.py --chunks ChamanChunk{2*,3*}SenAT144 --project ChamanBigSenAT144 --datatype velocity  --outdir mimtpy
```
it works fine.

**Comment by ranneylxr** [comment]
Hi @falkamelung 
Could you please paste the content of your template here?
It seems that there is something wrong in your template.
Thank you!
Xiaoran.

**Comment by falkamelung** [comment]
I have no mimtpy options in the *template file ....

In any case, writing filenames into the *template files is not a good idea....  I hope we can have the defaults take care of that... 
I'll wait...

**Comment by falkamelung** [comment]
I see that you use $SCRATCHDIR in the script. Lets avoid this.  We  should first have a version where all files are given with full path. Then, if —project is given it calls a module that sets the paths and does globs  to find the S1 file

Currently you would call it being in $SRATCHDIR. That is different to all our scripts.So the ‘normal way’ would be 

```
cd $SRATCHDIR/GujaratBigSenDT10
concatenate_chunks.py —chunks $SCRATCHDIR/GujaratChunk2{1,2,3}SenDT107  --datatype timeseries                                         --outdir mimtpy
concatenate_chunks.py —chunks $SCRATCHDIR/GujaratChunk2{1,2,3}SenDT107  --datatype timeseries -—project GujaratBigSenDT10             --outdir mimtpy
concatenate_chunks.py —chunks $SCRATCHDIR/GujaratChunk2{1,2,3}SenDT107  --datatype timeseries -—project $SCRATCHDIR/GujaratBigSenDT10 --outdir mimtpy
concatenate_chunks.py —chunks ../GujaratChunk2{1,2,3}SenDT107           --datatype timeseries                                         --outdir mimtpy
```
For convenience you could also call it::
```
cd $SRATCHDIR
concatenate_chunks.py —chunks GujaratChunk2{1,2,3}SenDT107              --datatype timeseries -—project GujaratBigSenDT10 --outdir mimtpy
concatenate_chunks.py —chunks GujaratChunk2{1,2,3}SenDT107              --datatype timeseries -—project $SCRATCHDIR/GujaratBigSenDT10 --outdir mimtpy
concatenate_chunks.py —chunks $SCRATCHDIR/GujaratChunk2{1,2,3}SenDT107  --datatype timeseries -—project SCRATCHDIR/GujaratBigSenDT10  --outdir mimtpy
```
I hope the convention is clear. If something is given without path it starts where you are. We just have to get this right once!

Falk

**Comment by falkamelung** [comment]
It works.  So I moved suggestions to the "suggestion issue" and closing this.

**Comment by falkamelung** [comment]
It works. So I moved suggestions to the "suggestion issue" and closing this.
